# Generated by Django 5.2.1 on 2025-05-12 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'Book'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='added_date',
        ),
    ]
