# Generated by Django 5.2.1 on 2025-05-12 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_alter_book_options_remove_book_added_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book'},
        ),
    ]
