# Generated by Django 5.2 on 2025-05-13 01:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_alter_book_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
