# Generated by Django 5.2 on 2025-05-13 02:11

import library_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_book_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=15, unique=True, validators=[library_app.models.validate_numeric]),
        ),
    ]
