# Generated by Django 5.2 on 2025-05-15 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0007_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
